### ISSUE TITLE
Not working on Strapi 4.11.5

### ISSUE THREAD

**Issue by kevinblanco** [ComfortablyCoding/strapi-plugin-slugify#103]
Hello. I have a project running on Strapi 4.11.2 using this plugin with no issues. After updating Strapi to 4.11.5 I have the following error: 

```
Error: Could not load js config file /node_modules/strapi-plugin-slugify/strapi-server.js: Cannot find module '@strapi/utils/lib/errors'
Require stack:
- node_modules/strapi-plugin-slugify/server/controllers/slug-controller.js
```

Node v16.20.1

**Comment by ComfortablyCoding** [comment]
This should already be fixed by #99 (released in v2.3.3). What version of the plugin are you using?

**Comment by ComfortablyCoding** [comment]
Cosing due to inactivity, will re-open if issue is reported to still exist.
